name: Deploy Pokerixe Back
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Push to GHCR"]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    name: Deploy sur le serveur labo
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Déployer sur le serveur labo
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
              echo '${{ secrets.GHCR_PAT }}' | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin &&
              docker pull ghcr.io/pokerixe/pokerixe-backend:latest &&
              cd ~/PROJET/ &&
              docker compose up -d --no-deps --force-recreate backend-pokerixe
            "
          rm private_key
